= livereload-gradle-plugin
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    livereload-gradle-plugin
:project-group:   org.kordamp.gradle
:project-version: 0.3.0
:livereload-url:            http://livereload.com/
:livereload-jvm-url:        https://github.com/davidB/livereload-jvm
:asciidoctor-gradle-plugin: https://github.com/asciidoctor/asciidoctor-gradle-plugin

image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

The {project-name} enables {livereload-url}[LiveReload] on a particular directory via {livereload-jvm-url}[livereload-jvm].

== Installation

Option #1
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath '{project-group}:{project-name}:{project-version}'
    }
}
apply plugin: '{project-group}.livereload'
----

Option #2
[source,groovy]
[subs="attributes"]
----
plugins {
    id '{project-group}.livereload' version '{project-version}'
}
----


== Usage

The plugin adds a new task named `liveReload`. This task exposes 2 properties as part of its configuration

[horizontal]
port:: used by the LiveReload Sever. Type: int. Default: 35729.
docRoot:: the main directory from which files will be served. Type: String. Default `build/livereload`

You'd usually run the `liveReload` task in a separate shell as the server is kept alive until the gradle
session is killed. Support for forking the JVM process and killing the server via a second command may
be added in a future release.

== Configuration

This plugin can be used in combination with any task that produces content that should be reload. In particular this
plugin detects if the {asciidoctor-gradle-plugin}[asciidoctor-gradle-plugin] is installed, automatically configuring
the `outputDir` of the `asciidoctor` task as the `docRoot`. This setting can be overridden by user input of course.

