LiveReload Gradle Plugin
=========================
:author: Andres Almiray
:version: 0.2.1
:livereload-url: http://livereload.com/
:livereload-jvm-url: https://github.com/davidB/livereload-jvm
:asciidoctor-gradle-plugin: https://github.com/asciidoctor/asciidoctor-gradle-plugin
:project-name: livereload-gradle-plugin

image:http://img.shields.io/travis/aalmiray/{project-name}/master.svg["Build Status", link="https://travis-ci.org/aalmiray/{project-name}"]
image:http://img.shields.io/coveralls/aalmiray/{project-name}/master.svg["Coverage Status", link="https://coveralls.io/r/aalmiray/{project-name}"]
image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]
image:https://api.bintray.com/packages/aalmiray/kordamp/{project-name}/images/download.svg[link="https://bintray.com/aalmiray/kordamp/{project-name}/_latestVersion"]

The {project-name} enables {livereload-url}[LiveReload] on a particular directory via {livereload-jvm-url}[livereload-jvm].

== Installation

Use the following snippet inside a Gradle build file:

[source,groovy]
.build.gradle
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.kordamp.gradle:{project-name}:{version}'
    }
}

apply plugin: 'org.kordamp.gradle.livereload'
----

== Usage

The plugin adds a new task named `liveReload`. This task exposes 2 properties as part of its configuration

[horizontal]
port:: used by the LiveReload Sever. Type: int. Default: 35729.
docRoot:: the main directory from which files will be served. Type: String. Default `build/livereload`

You'd usually run the `liveReload` task in a separate shell as the server is kept alive until the gradle
session is killed. Support for forking the JVM process and killing the server via a second command may
be added in a future release.

== Configuration

This plugin can be used in combination with any task that produces content that should be reload. In particular this
plugin detects if the {asciidoctor-gradle-plugin}[asciidoctor-gradle-plugin] is installed, automatically configuring
the `outputDir` of the `asciidoctor` task as the `docRoot`. This setting can be overridden by user input of course.

